### ISSUE TITLE
AR dependency locked to =4.2.0

### ISSUE THREAD

**Issue by jtippett** [JackDanger/permanent_records#52]
hi there, I noticed something strange when doing a library update. The new version of PR seems to have a hard dependency on the rather old AR 4.2.0: 

```
$ gem dependency permanent_records
Gem permanent_records-3.3.0
  activerecord (>= 3.0.0)
  rake (>= 0, development)

Gem permanent_records-4.0.0
  activerecord (= 4.2.0)
  activesupport (= 4.2.0)
  database_cleaner (>= 0, development)
  pry (>= 0, development)
  rspec (~> 2.14.1, development)
  sqlite3 (>= 0, development)
```

I see this also reported on rubygems: https://rubygems.org/gems/permanent_records

I don't see anything in the project that could explain this. Any clue as to what's going on?

**Comment by moorage** [comment]
+1 ... seems like it could be a >=

**Comment by mherold** [comment]
Everything is fine when installing the gem from github master.

@JackDanger It seems before building the gem to be uploaded to rubygems, an `unset AR_TEST_VERSION` is required; otherwise the gem metadata is built the locally set AR version. Maybe you could bump to 4.0.1, tag, build and upload to rubygems again?

**Comment by mherold** [comment]
This shouldn't be an issue any more.
